/**
 * MOOD local state.
 *
 * The CLI is a thin shell over a small on-disk state root:
 *
 *   ~/.mood/
 *     identity/
 *       node.json           ← public identity (node ID, public key, org)
 *       private.json        ← private Ed25519 key (mode 0600 if possible)
 *       public.json         ← Alpha 002 protocol identity (@mood/identity)
 *     config/
 *       node.json           ← runtime config: network, protocol, peers, org
 *     connector/
 *       connector-id        ← connector identity (@mood/connector layer)
 *       agent-record.json   ← registered AI Agents (names/types only)
 *     contributions/
 *       events/             ← ContributionEvents (@mood/contribution-proof layer)
 *       proofs/             ← ContributionProofs (SHA-256 over each event)
 *     snapshots/
 *       latest.json         ← pointer to the most recent snapshot
 *       snapshot-*.json     ← snapshot objects written by the runtime
 *     logs/
 *       node.log            ← append-only runtime log
 *       api.log             ← append-only node-api (Agent Layer) log
 *     state.json            ← ephemeral state: status, pid, started_at
 *     api-state.json        ← node-api state: status, pid, port, bind
 *     api-stop              ← cooperative stop flag for the API server
 *
 * Identity material is generated by @mood/node-runtime (same Ed25519
 * scheme, same Node ID derivation as every other MOOD client) and
 * activated as the Alpha 002 protocol identity by @mood/identity — one
 * keypair, shared by both layers. The CLI does not implement its own
 * crypto.
 *
 * All I/O is local-only. The protocol layer remains unchanged.
 */

import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
  readdirSync,
  chmodSync,
} from 'fs';
import { join } from 'path';
import { homedir } from 'os';
import {
  generateKeypair,
  generateNodeId,
  generateOrganizationId,
} from '@mood/node-runtime';
import {
  createIdentity,
  loadPublicIdentity,
  identityPaths,
} from '@mood/identity';
import {
  NETWORK_NAME,
  NETWORK_ID,
  PROTOCOL_VERSION,
  RELAY_URL,
  INITIAL_EPOCH,
  GENESIS_PEERS,
  DEFAULT_ORGANIZATION,
} from './config/defaults.js';

// ── Paths ───────────────────────────────────────────────────────────────────

export function moodHome() {
  return process.env.MOOD_HOME || join(homedir(), '.mood');
}

export function moodPaths() {
  const root = moodHome();
  return {
    root,
    identityDir: join(root, 'identity'),
    configDir: join(root, 'config'),
    snapshotsDir: join(root, 'snapshots'),
    logsDir: join(root, 'logs'),
    identityFile: join(root, 'identity', 'node.json'),
    privateFile: join(root, 'identity', 'private.json'),
    configFile: join(root, 'config', 'node.json'),
    snapshotsDirPath: join(root, 'snapshots'),
    latestSnapshotFile: join(root, 'snapshots', 'latest.json'),
    logFile: join(root, 'logs', 'node.log'),
    apiLogFile: join(root, 'logs', 'api.log'),
    stateFile: join(root, 'state.json'),
    apiStateFile: join(root, 'api-state.json'),
    stopFlagFile: join(root, 'stop'),
    apiStopFlagFile: join(root, 'api-stop'),
  };
}

/**
 * Make the full ~/.mood/ tree. Idempotent.
 */
export function ensureMoodHome() {
  const p = moodPaths();
  for (const d of [p.identityDir, p.configDir, p.snapshotsDir, p.logsDir]) {
    mkdirSync(d, { recursive: true });
  }
  return p;
}

/**
 * Has the user already run `mood init`?
 */
export function isInitialized() {
  const p = moodPaths();
  return existsSync(p.identityFile) && existsSync(p.privateFile);
}

/**
 * Read public identity. Returns null if not initialized.
 */
export function readIdentity() {
  const p = moodPaths();
  if (!existsSync(p.identityFile)) return null;
  try {
    return JSON.parse(readFileSync(p.identityFile, 'utf8'));
  } catch {
    return null;
  }
}

/**
 * Read the private identity record. NEVER expose this through a command —
 * only the local daemon and invitation signing read it.
 * Returns null if not initialized.
 */
export function readPrivateIdentity() {
  const p = moodPaths();
  if (!existsSync(p.privateFile)) return null;
  try {
    return JSON.parse(readFileSync(p.privateFile, 'utf8'));
  } catch {
    return null;
  }
}

/**
 * Read config (network, protocol, peers list). Returns null if missing.
 */
export function readConfig() {
  const p = moodPaths();
  if (!existsSync(p.configFile)) return null;
  try {
    return JSON.parse(readFileSync(p.configFile, 'utf8'));
  } catch {
    return null;
  }
}

/**
 * Read ephemeral runtime state (status, pid, etc).
 */
export function readState() {
  const p = moodPaths();
  if (!existsSync(p.stateFile)) return { status: 'Stopped' };
  try {
    return JSON.parse(readFileSync(p.stateFile, 'utf8'));
  } catch {
    return { status: 'Stopped' };
  }
}

/**
 * Write ephemeral runtime state.
 */
export function writeState(state) {
  const p = ensureMoodHome();
  writeFileSync(p.stateFile, JSON.stringify(state, null, 2));
}

/**
 * Is a process with this pid alive? (pid 0/null → false)
 */
export function isProcessAlive(pid) {
  if (!pid || typeof pid !== 'number') return false;
  try {
    process.kill(pid, 0);
    return true;
  } catch (err) {
    // ESRCH = no such process; EPERM on Windows for dead pids of other
    // users. Anything other than a successful probe means "not alive"
    // for our purposes.
    return err.code === 'EPERM' ? true : false;
  }
}

/**
 * Effective status: reconciles the on-disk state with process reality.
 * If state.json claims Running but the pid is gone, repairs the file.
 */
export function effectiveStatus() {
  const st = readState();
  if (st.status === 'Running') {
    if (isProcessAlive(st.pid)) {
      return 'Running';
    }
    writeState({ ...st, status: 'Stopped', pid: null, stoppedAt: new Date().toISOString() });
    return 'Stopped';
  }
  return st.status || 'Stopped';
}

/**
 * Read the latest snapshot pointer, or null.
 */
export function readLatestSnapshot() {
  const p = moodPaths();
  if (!existsSync(p.latestSnapshotFile)) return null;
  try {
    return JSON.parse(readFileSync(p.latestSnapshotFile, 'utf8'));
  } catch {
    return null;
  }
}

/**
 * Persist the latest snapshot pointer.
 */
export function writeLatestSnapshot(snapshot) {
  const p = ensureMoodHome();
  writeFileSync(p.latestSnapshotFile, JSON.stringify(snapshot, null, 2));
}

/**
 * Load the full snapshot object referenced by the latest pointer,
 * falling back to the highest-epoch snapshot file on disk.
 * Returns null when the node has no snapshot yet.
 */
export function readLatestSnapshotObject() {
  const p = moodPaths();
  const load = (file) => {
    try {
      return JSON.parse(readFileSync(file, 'utf8'));
    } catch {
      return null;
    }
  };

  const pointer = readLatestSnapshot();
  if (pointer && pointer.snapshotFile) {
    const snap = load(join(p.snapshotsDirPath, pointer.snapshotFile));
    if (snap) return snap;
  }

  if (!existsSync(p.snapshotsDirPath)) return null;
  let best = null;
  for (const f of readdirSync(p.snapshotsDirPath)) {
    if (!f.endsWith('.json') || f === 'latest.json') continue;
    const snap = load(join(p.snapshotsDirPath, f));
    if (snap && (!best || (snap.epochNumber || 0) > (best.epochNumber || 0))) {
      best = snap;
    }
  }
  return best;
}

// ── Identity creation ──────────────────────────────────────────────────────

/**
 * Initialize the local node. Creates directories, generates (or adopts)
 * an Ed25519 identity, writes the public and private records, activates
 * the Alpha 002 protocol identity over the same key, and writes a
 * default runtime config.
 *
 * Idempotent: if the node is already initialized, it returns the
 * existing identity rather than regenerating.
 *
 * One node, one key — three paths, all converging on a single keypair:
 *   - already initialized            → activate the protocol layer over
 *                                      the existing private.json
 *   - private.json exists, node.json missing (the user ran
 *     `mood identity create` first) → ADOPT that key; never regenerate
 *   - nothing exists                 → generate fresh, then activate
 */
export function initIdentity({ organizationId, organizationName, organizationDomain } = {}) {
  ensureMoodHome();
  const p = moodPaths();

  if (isInitialized()) {
    // Existing node: bring the protocol layer up over the same key.
    activateProtocolIdentity();
    return {
      created: false,
      identity: readIdentity(),
      paths: p,
    };
  }

  // Keypair + Node ID come from the shared runtime — identical derivation
  // to every other MOOD client (Ed25519 + sha256 over network-scoped input).
  const existingPrivate = readLocalPrivateRecord(p.privateFile);
  let publicKey;
  let secretKey = null; // null on adoption — the existing record is kept
  let createdAt;

  if (existingPrivate) {
    // A protocol identity created first owns the key: adopt it.
    const secret = Buffer.from(existingPrivate.privateKey, 'base64');
    if (secret.length !== 64) {
      throw new Error(
        'existing private.json privateKey is not a 64-byte Ed25519 secret key — resolve manually; refusing to overwrite it'
      );
    }
    publicKey = secret.subarray(32).toString('base64');
    createdAt = existingPrivate.createdAt || new Date().toISOString();
  } else {
    const keypair = generateKeypair();
    publicKey = keypair.publicKey;
    secretKey = keypair.secretKey;
    createdAt = new Date().toISOString();
  }

  const nodeId = generateNodeId(publicKey, NETWORK_ID);

  const publicRecord = {
    nodeId,
    publicKey,
    algorithm: 'ed25519',
    networkId: NETWORK_ID,
    createdAt,
    organizationId: organizationId || null,
    protocolVersion: PROTOCOL_VERSION,
    clientVersion: 'mood-cli/0.2.0-alpha.2',
  };

  writeFileSync(p.identityFile, JSON.stringify(publicRecord, null, 2));
  if (secretKey) {
    const privateRecord = {
      nodeId,
      privateKey: secretKey,
      algorithm: 'ed25519',
      createdAt,
      warning: 'KEEP LOCAL. Never share this file. Never commit it.',
    };
    writeFileSync(p.privateFile, JSON.stringify(privateRecord, null, 2));
    try {
      chmodSync(p.privateFile, 0o600); // POSIX only; harmless on Windows
    } catch {
      // chmod unsupported on some filesystems — file stays private by
      // user-profile isolation.
    }
  }

  const orgName = organizationName || DEFAULT_ORGANIZATION.name;
  const orgDomain = organizationDomain || DEFAULT_ORGANIZATION.domain;
  const orgId = organizationId
    || generateOrganizationId(orgName, orgDomain); // deterministic default

  // Default runtime config.
  const cfg = {
    network: NETWORK_NAME,
    networkId: NETWORK_ID,
    protocolVersion: PROTOCOL_VERSION,
    clientVersion: 'mood-cli/0.2.0-alpha.2',
    relayUrl: RELAY_URL,
    organization: {
      organizationId: orgId,
      name: orgName,
      domain: orgDomain,
    },
    bootstrapPeers: GENESIS_PEERS.map((peer) => ({ ...peer })),
    epoch: INITIAL_EPOCH,
    createdAt,
  };
  writeFileSync(p.configFile, JSON.stringify(cfg, null, 2));

  // Initial ephemeral state.
  writeState({ status: 'Stopped', startedAt: null, pid: null });

  // Alpha 002-B: activate the protocol identity over the same key —
  // createIdentity() adopts the private record this node owns (fresh:
  // the one written above; adopted: the one `mood identity create`
  // wrote) and writes ~/.mood/identity/public.json.
  const protocolIdentity = activateProtocolIdentity();
  if (protocolIdentity && protocolIdentity.publicKey !== publicKey) {
    throw new Error(
      `protocol identity mismatch: ${identityPaths().publicFile} carries a different key than ${p.privateFile} — resolve manually before continuing`
    );
  }

  return { created: true, identity: publicRecord, paths: p };
}

/**
 * Read the local private identity record. Returns null when absent.
 * A present-but-unreadable record is an error, never an invitation to
 * overwrite the node's key material.
 */
function readLocalPrivateRecord(privateFile) {
  if (!existsSync(privateFile)) return null;
  let record;
  try {
    record = JSON.parse(readFileSync(privateFile, 'utf8'));
  } catch (err) {
    throw new Error(
      `cannot read existing private identity (${privateFile}): ${err.message} — resolve manually; refusing to overwrite it`
    );
  }
  if (!record || typeof record.privateKey !== 'string') {
    throw new Error(
      `existing private identity (${privateFile}) carries no privateKey — resolve manually; refusing to overwrite it`
    );
  }
  return record;
}

/**
 * One node, one key: the Alpha 002 protocol identity (@mood/identity)
 * lives over the SAME private.json this CLI owns. public.json is
 * activated by adopting that key — never by generating a second one.
 * Returns the protocol public identity, or null when no key exists.
 */
export function activateProtocolIdentity() {
  const paths = identityPaths();
  const existing = loadPublicIdentity();
  if (existing) return existing; // already active — never rekey
  if (!existsSync(paths.privateFile)) return null;
  const { identity } = createIdentity(); // adopts private.json
  return identity;
}

/**
 * Enroll the node into an organization (sets memberSubjectId-style
 * affiliation on the public record). Used by invitation acceptance and
 * org configuration.
 */
export function setOrganization(organizationId) {
  const identity = readIdentity();
  if (!identity) {
    throw new Error('Node not initialized — run `mood init` first');
  }
  identity.organizationId = organizationId;
  identity.enrolledAt = new Date().toISOString();
  writeFileSync(moodPaths().identityFile, JSON.stringify(identity, null, 2));
  return identity;
}

// ── Convenience: load everything for `mood status` etc. ───────────────────

export function loadState() {
  const id = readIdentity();
  const cfg = readConfig();
  const st = readState();
  const snap = readLatestSnapshot();
  const status = effectiveStatus();

  return {
    nodeId: id ? id.nodeId : null,
    organizationId: id ? id.organizationId : null,
    publicKey: id ? id.publicKey : null,
    network: cfg ? cfg.network : NETWORK_NAME,
    networkId: cfg ? cfg.networkId : NETWORK_ID,
    protocolVersion: cfg ? cfg.protocolVersion : PROTOCOL_VERSION,
    relayUrl: cfg ? cfg.relayUrl : RELAY_URL,
    status,
    startedAt: st.startedAt || null,
    pid: st.pid || null,
    peers: (st.connectedPeers || []).length,
    connectedPeers: st.connectedPeers || [],
    epoch: (snap && snap.epochNumber) || (cfg ? cfg.epoch || INITIAL_EPOCH : INITIAL_EPOCH),
    digest: snap ? snap.digest : null,
    agreement: snap ? (snap.agreement || null) : null,
  };
}
